
### model
model_name_or_path: /kaggle/working/models/Qwen3-8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora

lora_rank: 32
lora_alpha: 128
lora_dropout: 0.05
lora_target: all

quantization_bit: 4
quantization_type: nf4

### dataset
dataset: kalimcoder_sft
template: qwen
cutoff_len: 2048
max_samples: 50000

### output
output_dir: /kaggle/working/KalimCoder/checkpoints/qwen3-lora

logging_steps: 10
save_steps: 200
save_total_limit: 3

### training
per_device_train_batch_size: 1
gradient_accumulation_steps: 32

learning_rate: 2e-4
num_train_epochs: 3

fp16: true

gradient_checkpointing: true

### optimizer
optim: paged_adamw_8bit

### distributed
ddp_timeout: 180000000

### hub
push_to_hub: false

ddp_find_unused_parameters: false

upcast_layernorm: true
