"""
src/data/quality.py — Dataset quality scoring for the KalimCoder pipeline.

:class:`QualityScorer` assigns a float score ``[0.0, 1.0]`` to every
:class:`~src.data.schema.CanonicalExample`.  The score is stored in the
``quality_score`` field and persisted in output parquet files for downstream
filtering or curriculum-learning weighting.

Score composition (weighted sum of sub-scores, all in ``[0.0, 1.0]``)::

    Sub-score            Weight  Signal
    ──────────────────── ──────  ────────────────────────────────────────────
    token_score           0.25   Linear ramp-up/down within [min, max] tokens
    alpha_score           0.20   Fraction of alphanumeric + common chars
    comment_ratio_score   0.20   Penalises >max_comment_ratio comment lines
    autogen_score         0.20   0 if autogenerated pattern detected, else 1
    language_score        0.15   0.5 for "unknown", 1.0 for known languages

Design notes
------------
* All scoring is deterministic and stateless — the scorer holds only compiled
  regex patterns and config values.
* ``annotate()`` is the preferred entry point: it returns a *new*
  ``CanonicalExample`` with ``quality_score`` filled in (immutable by design).
* The scorer is intentionally **not** a HuggingFace map function — it operates
  on :class:`~src.data.schema.CanonicalExample` objects to stay decoupled from
  the HF library and work inside generators.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field, replace

from src.data.schema import CanonicalExample

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Approximate chars-per-token (GPT-2 / Qwen empirical mean)
_CHARS_PER_TOKEN: float = 4.0

# Single-line comment prefixes across common languages
_COMMENT_PREFIXES: tuple[str, ...] = ("#", "//", "--", ";", "%", "/*", "*", "\"\"\"", "'''")

# Languages always considered "known" (not penalised)
_KNOWN_LANGUAGES: frozenset[str] = frozenset({
    "python", "javascript", "typescript", "java", "c", "c++", "c#", "go",
    "rust", "ruby", "php", "swift", "kotlin", "scala", "r", "matlab",
    "shell", "bash", "sql", "html", "css", "markdown", "haskell",
    "ocaml", "erlang", "elixir", "clojure", "julia", "lua", "perl",
})

# Default autogenerated-file regex patterns
_DEFAULT_AUTOGEN_PATTERNS: list[str] = [
    r"auto[-_]?generated",
    r"\bdo\s+not\s+edit\b",
    r"generated\s+by\b",
    r"@generated",
    r"this\s+file\s+is\s+generated",
    r"machine[-_]generated",
    r"automatically\s+generated",
]


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclass
class QualityConfig:
    """Parameters controlling quality scoring and the minimum threshold."""

    # Minimum score to keep an example (drop if score < this)
    min_quality_score: float = 0.30

    # Output token bounds (estimated as len(text) / _CHARS_PER_TOKEN)
    min_tokens: int = 10
    max_tokens: int = 8192

    # Minimum fraction of alphanumeric / common whitespace chars
    min_alpha_ratio: float = 0.25

    # Maximum fraction of comment lines (more → likely docs, not code)
    max_comment_ratio: float = 0.80

    # Heuristic language confidence threshold
    min_language_confidence: float = 0.50

    # Regex patterns scanned against the first 2 000 chars of the output
    autogen_patterns: list[str] = field(
        default_factory=lambda: list(_DEFAULT_AUTOGEN_PATTERNS)
    )

    # Sub-score weights (must sum to 1.0)
    weight_tokens: float = 0.25
    weight_alpha: float = 0.20
    weight_comment: float = 0.20
    weight_autogen: float = 0.20
    weight_language: float = 0.15


# ---------------------------------------------------------------------------
# Scorer
# ---------------------------------------------------------------------------


class QualityScorer:
    """Assigns quality scores to :class:`~src.data.schema.CanonicalExample` objects.

    Parameters
    ----------
    config:
        :class:`QualityConfig` instance.  Defaults to ``QualityConfig()`` if
        not provided.
    """

    def __init__(self, config: QualityConfig | None = None) -> None:
        self._cfg = config or QualityConfig()
        # Pre-compile autogen regex for performance
        patterns = self._cfg.autogen_patterns
        self._autogen_re: re.Pattern | None = (
            re.compile("|".join(patterns), re.IGNORECASE) if patterns else None
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def score(self, example: CanonicalExample) -> float:
        """Return a quality score ``[0.0, 1.0]`` for *example*.

        Scoring is based on the ``output`` field (the training target).
        """
        text = example.output
        cfg = self._cfg

        tok = self._token_score(text, cfg.min_tokens, cfg.max_tokens)
        alp = self._alpha_score(text)
        cmt = self._comment_ratio_score(text, cfg.max_comment_ratio)
        aut = self._autogen_score(text)
        lng = self._language_score(example.language)

        return (
            cfg.weight_tokens   * tok
            + cfg.weight_alpha  * alp
            + cfg.weight_comment * cmt
            + cfg.weight_autogen * aut
            + cfg.weight_language * lng
        )

    def passes(self, example: CanonicalExample) -> bool:
        """Return ``True`` if *example* meets the minimum quality threshold."""
        return self.score(example) >= self._cfg.min_quality_score

    def annotate(self, example: CanonicalExample) -> CanonicalExample:
        """Return a new :class:`CanonicalExample` with ``quality_score`` filled in.

        The original *example* is never modified.
        """
        return replace(example, quality_score=round(self.score(example), 4))

    # ------------------------------------------------------------------
    # Sub-scores (package-private for testing)
    # ------------------------------------------------------------------

    def _token_score(self, text: str, min_tok: int, max_tok: int) -> float:
        """Linear ramp within [min_tok, max_tok]; 0 outside the range."""
        if not text:
            return 0.0
        n = len(text) / _CHARS_PER_TOKEN
        if n < min_tok or n > max_tok:
            return 0.0
        rng = float(max(max_tok - min_tok, 1))
        low_ramp = min_tok + 0.10 * rng
        high_ramp = min_tok + 0.90 * rng
        if n <= low_ramp:
            return (n - min_tok) / max(low_ramp - min_tok, 1e-9)
        if n >= high_ramp:
            return (max_tok - n) / max(max_tok - high_ramp, 1e-9)
        return 1.0

    def _alpha_score(self, text: str) -> float:
        """Fraction of alphanumeric + common structural chars; partial credit below threshold."""
        if not text:
            return 0.0
        good = sum(
            1 for c in text
            if c.isalnum() or c in " \t\n\r_.,()[]{}:;\"'=-+*/\\|<>!@#$%^&~`"
        )
        ratio = good / len(text)
        threshold = self._cfg.min_alpha_ratio
        if ratio < threshold:
            return ratio / max(threshold, 1e-9)
        return 1.0

    def _comment_ratio_score(self, text: str, max_ratio: float) -> float:
        """Score 1.0 unless comment line fraction exceeds *max_ratio*."""
        lines = text.splitlines()
        if not lines:
            return 0.0
        stripped = [l.strip() for l in lines if l.strip()]
        if not stripped:
            return 0.0
        comment_count = sum(
            1 for l in stripped if l.startswith(_COMMENT_PREFIXES)
        )
        ratio = comment_count / len(stripped)
        if ratio > max_ratio:
            excess = ratio - max_ratio
            return max(0.0, 1.0 - excess / max(1.0 - max_ratio, 1e-9))
        return 1.0

    def _autogen_score(self, text: str) -> float:
        """Return ``0.0`` if an autogenerated-file pattern is detected, else ``1.0``."""
        if self._autogen_re is None:
            return 1.0
        # Scan only the first 2 000 chars for performance
        return 0.0 if self._autogen_re.search(text[:2000]) else 1.0

    def _language_score(self, language: str) -> float:
        """Return ``1.0`` for known languages, ``0.5`` for unknown."""
        lang = language.lower().strip()
        return 1.0 if lang in _KNOWN_LANGUAGES else 0.5
